/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package com.mulesoft.module.dropbox;

import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.oauth.*;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.mule.api.annotations.param.Payload;


import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.api.client.config.ClientConfig;
import com.sun.jersey.api.client.config.DefaultClientConfig;
import com.sun.jersey.core.header.FormDataContentDisposition;
import com.sun.jersey.multipart.FormDataBodyPart;
import com.sun.jersey.multipart.FormDataMultiPart;
import com.sun.jersey.multipart.MultiPart;
import com.sun.jersey.multipart.impl.MultiPartWriter;

import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.ws.rs.core.MediaType;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;

/**
 * Dropbox Cloud Connector.
 * The Dropbox Connector will allow to use the Dropbox REST API. Almost every operation that can be done via the API can be done thru this connector.
 * 
 * @author MuleSoft, Inc.
 */
@Connector(name = "dropbox", schemaVersion = "3.3.0", friendlyName = "Dropbox", minMuleVersion = "3.3")
@OAuth2(authorizationUrl = "https://www.dropbox.com/1/oauth2/authorize",
		accessTokenUrl = "https://api.dropbox.com/1/oauth2/token",
        accessTokenRegex = "\"access_token\"[ ]*:[ ]*\"([^\\\"]*)\"",
        expirationRegex = "\"expires_in\"[ ]*:[ ]*([\\d]*)",
        refreshTokenRegex = "\"refresh_token\"[ ]*:[ ]*\"([^\\\"]*)\"")
public class DropboxConnector {
    private static final String API_VERSION = "1";
    private static final String ROOT_PARAM = "dropbox";
    private static final String API_CONTENT_URL = "files/" + ROOT_PARAM;

    private String accessTokenIdentifier;

	/**
	 * URL of the Dropbox server API
	 */
	@Configurable
	@Optional
	@Default("api.dropbox.com")
	private String server;

	/**
	 * URL of the Dropbox server content API
	 */
	@Configurable
	@Optional
	@Default("api-content.dropbox.com")
	private String contentServer;

	/**
	 * Dropbox server port
	 */
	@Configurable
	@Optional
	@Default("80")
	private int port;

	/**
	 * Application key
	 */
	@Configurable
	@OAuthConsumerKey
	private String appKey;

	/**
	 * Application secret
	 */
	@Configurable
	@OAuthConsumerSecret
	private String appSecret;

	@OAuthAccessToken
	private String accessToken;

	private Client client;

    @OAuthAccessTokenIdentifier
    public String getOAuthTokenAccessIdentifier() throws Exception {
        if (this.accessTokenIdentifier == null) {
            this.accessTokenIdentifier = this.getUserId();
        }

        return this.accessTokenIdentifier;
    }

	/**
	 * Upload file to Dropbox. The payload is an InputStream containing bytes of
	 * the data to be uploaded.
	 * 
	 * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:upload-file}
	 * 
	 * @param fileDataObj
	 *            file to be uploaded
	 * @param overwrite
	 * 				overwrite file in case it already exists           
	 * @param path
	 *            The destination path
	 * @param filename
	 *            The destination file name
	 * 
	 * @return http response
	 * @throws Exception
	 *             exception
	 */
//	@SuppressWarnings("resource")
    @Processor
	@OAuthProtected
	public String uploadFile(@Payload InputStream fileDataObj,
							@Optional @Default("true") Boolean overwrite,
							String path,
							String filename) throws Exception {
		
		final InputStream fileData = (InputStream) fileDataObj;

		final String apiUrl = getApiContentUrl(path);

		final FormDataBodyPart formDataBodyPart = new FormDataBodyPart(fileData, MediaType.APPLICATION_OCTET_STREAM_TYPE);
		MultiPart parts = new FormDataMultiPart().bodyPart(formDataBodyPart);

		formDataBodyPart.setContentDisposition(FormDataContentDisposition
				.name("file")
				.fileName(filename)
				.size(fileData.available())
				.modificationDate(new Date()).build());

		WebResource r = getClient().resource(constructUri(getContentServer(), apiUrl, 
                String.format("file=%s&overwrite=%s&access_token=%s", filename, overwrite.toString(), getAccessToken())));
		
		String response = r.type(MediaType.MULTIPART_FORM_DATA_TYPE).post(
				String.class, parts);

		return response;
	}

	/**
	 * Create new folder on Dropbox
	 * 
	 * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:create-folder}
	 * 
	 * @param path
	 *            full path of the folder to be created
	 * 
	 * @return http response
	 * @throws Exception
	 *             exception
	 */
	@Processor
	@OAuthProtected
	public String createFolder(String path) throws Exception {
		final String apiUrl = "fileops/create_folder";

		WebResource r = getClient().resource(constructUri(getServer(), apiUrl, 
		        String.format("root=%s&path=%s&access_token=%s", ROOT_PARAM, path, getAccessToken())));
		
		String response = r.post(String.class);

		return response;
	}

	/**
	 * Deletes a file or folder.
	 * 
	 * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:delete}
	 * 
	 * @param path
	 *            full path to the file to be deleted
	 * 
	 * @return http response
	 * @throws Exception
	 *             exception
	 */
	@Processor
	@OAuthProtected
	public String delete(String path) throws Exception {
		final String apiUrl = "fileops/delete";

		WebResource r = getClient().resource(constructUri(getServer(), apiUrl, 
		        String.format("root=%s&path=%s&access_token=%s", ROOT_PARAM, path, getAccessToken())));
		r.accept(MediaType.APPLICATION_JSON_TYPE).type(
				MediaType.APPLICATION_FORM_URLENCODED_TYPE);

		String response = r.post(String.class);

		return response;
	}

	/**
	 * Downloads a file from Dropbox
	 * 
	 * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:download-file}
	 * 
	 * @param path
	 *            path to the file
	 * @param delete
	 *            delete the file on the Dropbox after download (ignored if
	 *            moveTo is set)
	 *
	 * @return Stream containing the downloaded file data
	 * @throws Exception
	 *             exception
	 */
	@Processor
	@OAuthProtected
	public InputStream downloadFile(String path,
			@Optional @Default("false") boolean delete) throws Exception {
		final String apiUrl = getApiContentUrl(path);

		WebResource r = getClient().resource(constructUri(getContentServer(), apiUrl, String.format("access_token=%s", getAccessToken())));

		InputStream response = r.get(InputStream.class);

		if (delete)
			delete(path);
		return response;
	}

	/**
	 * Lists the content of the remote directory
	 * 
	 * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:list}
	 * 
	 * @param path
	 *            path to the remote directory
	 * 
	 * @return List of files and/or folders
	 * @throws Exception
	 *             exception
	 */
	@Processor
	@OAuthProtected
	public List<String> list(String path) throws Exception {
		final String apiUrl = "metadata/dropbox/" + adaptPath(path);

		WebResource r = getClient().resource(constructUri(getServer(), apiUrl, String.format("access_token=%s", getAccessToken())));

		String response = r.get(String.class);
		final JSONObject root = (JSONObject) JSONValue.parse(response);
		final JSONArray files = (JSONArray) root.get("contents");
		List<String> paths = new ArrayList<String>(files.size());
		for (int i = 0; i < files.size(); i++) {
			JSONObject file = (JSONObject) files.get(i);
			paths.add(file.get("path").toString());
		}
		return paths;
	}

	/**
	 * Moves a file or folder to a new location.
	 * 
	 * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:move}
	 * 
	 * @param from
	 *            Specifies the file or folder to be moved from, relative to
	 *            root.
	 * @param to
	 *            Specifies the destination path, including the new name for the
	 *            file or folder, relative to root.
	 *            
	 * @return http response
	 * @throws Exception
	 *             exception
	 */
	@Processor
	@OAuthProtected
	public String move(String from, String to) throws Exception {
		from = adaptPath(from);
		to = adaptPath(to);
		final String apiUrl = "fileops/move";

		WebResource r = getClient().resource(constructUri(getServer(), apiUrl, 
		        String.format("root=%s&from_path=%s&to_path=%s&access_token=%s", ROOT_PARAM, from, to, getAccessToken())));

		String response = r.post(String.class);

		return response;
	}
	
	/**
     * Copies a file or folder to a new location.
     * 
     * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:copy}
     * 
     * @param from
     *            Specifies the file or folder to be copied from, relative to
     *            root.
     * @param to
     *            Specifies the destination path, including the new name for the
     *            file or folder, relative to root.
     *            
     * @return http response
     * @throws Exception
     *             exception
     */
    @Processor
    @OAuthProtected
    public String copy(String from, String to) throws Exception {
        from = adaptPath(from);
        to = adaptPath(to);
        final String apiUrl = "fileops/copy";

        WebResource r = getClient().resource(constructUri(getServer(), apiUrl, 
                String.format("root=%s&from_path=%s&to_path=%s&access_token=%s", ROOT_PARAM, from, to, getAccessToken())));

        String response = r.post(String.class);

        return response;
    }

	/**
	 * Creates and returns a Dropbox link to files or folders users can use to view a preview of the file in a web browser.
	 * 
	 * {@sample.xml ../../../doc/Dropbox-connector.xml.sample dropbox:get-link}
	 * 
	 * @param path The path to the file or folder you want to link to.
	 * @param shortUrl Boolean indicating if the url returned will be shortened using the Dropbox url shortener (when true) or will link directly to the file's preview page (when false).
	 * @return String. A Dropbox link to the given path.
	 * 
	 * @throws Exception exception
	 */
	@Processor
	@OAuthProtected
	public String getLink(String path, @Optional @Default("true") Boolean shortUrl) throws Exception {
		path = adaptPath(path);
		final String apiUrl = "shares/dropbox/" + adaptPath(path);
		
		WebResource r = getClient().resource(constructUri(getServer(), apiUrl, 
		        String.format("short_url=%s&access_token=%s", shortUrl.toString(), getAccessToken())));
		
		String response = r.post(String.class);
		
		return response;
	}

    private String getUserId() throws Exception {
        final String apiUrl = "account/info";

        WebResource r = getClient().resource(constructUri(getServer(), apiUrl, String.format("access_token=%s", getAccessToken())));

        String response = r.get(String.class);

        final JSONObject root = (JSONObject) JSONValue.parse(response);
        final String uid = root.get("uid").toString();
        return uid;
    }

	// --------------------------------------

	public String getServer() {
		return server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	public String getContentServer() {
		return contentServer;
	}

	public void setContentServer(String contentServer) {
		this.contentServer = contentServer;
	}

	public int getPort() {
		return port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getAppKey() {
		return appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	public String getAppSecret() {
		return appSecret;
	}

	public void setAppSecret(String appSecret) {
		this.appSecret = appSecret;
	}

	/**
	 * @param path
	 */
	protected String getApiContentUrl(String path) {
	    return API_CONTENT_URL + "/" + adaptPath(path);
	}

	protected Client getClient() {
		if (client == null) {
			ClientConfig cc = new DefaultClientConfig();
			cc.getClasses().add(MultiPartWriter.class);
			client = Client.create(cc);
		}
		return client;
	}
	
	public String getAccessToken() {
		return accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	private String adaptPath(String path) {
		if (path.startsWith("/")) {
			path = path.substring(1);
		}
		return path;
	}
	
	private URI constructUri(String server, String apiUrl, String params) 
	        throws URISyntaxException {
	    String path = String.format("/%s/%s", API_VERSION, apiUrl);
        return new URI("https", server, path, params, null);
	}
}
