/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.dropbox;

import org.apache.commons.io.IOUtils;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.List;

public class DropboxTestCase
{
    protected static DropboxCloudConnector connector;

    @BeforeClass
    public static void setUp() throws Exception
    {
        connector = new DropboxCloudConnector();
        connector.setUserEmail("aperepel@gmail.com");
        connector.setUserPassword("dropbox");
        connector.setAppKey("n0cjz91u44k2kmb");
        connector.setAppSecret("nrtgv2ccewp8w4o");
        connector.setDebug(true);
        connector.initialise();
    }

    @AfterClass
    public static void tearDown()
    {
        if (connector != null)
        {
            connector.dispose();
        }
    }

    @Test
    public void testCreateFolder() throws Exception
    {
        connector.createFolder("Misc/ApiFolder");
    }

    @Test
    public void testUploadFile() throws Exception
    {
        connector.uploadFile(new ByteArrayInputStream("123451111111".getBytes()),
                "Misc/ApiFolder2", "myfilename1.txt");
    }

    @Test
    public void testListDirContents() throws Exception
    {
        final List<String> results = connector.list("Misc/ApiFolder2");
        for (String result : results)
        {
            System.out.println("result = " + result);
        }
    }

    @Test
    public void testDownloadFile() throws Exception
    {
        final InputStream results = connector.downloadFile("Misc/ApiFolder2/in/file1.txt");
        System.out.println(IOUtils.toString(results));

        connector.downloadFile("/Misc/ApiFolder2/in/file1.txt");
        System.out.println(IOUtils.toString(results));
    }

    @Test
    public void testMoveFile() throws Exception
    {
        connector.moveFile("Misc/ApiFolder2/in/file2.txt", "Misc/ApiFolder2/processed/file2.txt");
    }

}
